feat(ssi-modal.js): update keymap
InPageEdit/Plugins pull request #20
Opened 2022-02-08 11:27 UTC by bhsd-harry

Prepare for inpageedit/inpageedit-v2#29

2022-03-12 08:59 UTC, Dragon-Fish requested changes

2022-03-12 08:59 UTC, Dragon-Fish commented on lib/ssi-modal/ssi-modal.js
> +   * @param {jQuery} $modalWindow -the modalWindow element where buttons are appended to
类型有误，应为 `JQuery<HTMLElement>`

2022-03-12 08:59 UTC, Dragon-Fish commented on lib/ssi-modal/ssi-modal.js
> +   * @param {jQuery} $modalWindow -the modalWindow element where the button is appended to
同上

2022-03-12 09:09 UTC, Dragon-Fish commented
我理解一下这个PR所做的修改：

1. 为 confirm 的确认取消添加了快捷键
2. 修改了快捷键的逻辑，使快捷键按下时一定作用于最后打开的模态框，以便IPE能够使用`ctrl-s`进行保存

是这个意思吗

2022-03-12 09:21 UTC, bhsd-harry commented
> 我理解一下这个PR所做的修改：
> 
>     1. 为 confirm 的确认取消添加了快捷键
> 
>     2. 修改了快捷键的逻辑，使快捷键按下时一定作用于最后打开的模态框，以便IPE能够使用`ctrl-s`进行保存
> 
> 
> 是这个意思吗

1. 增加一种快捷键作用机制。以前的机制为只要在页面任意位置按下快捷键，则所有绑定该快捷键的模态框都会生效；现在这种机制需要额外设置 `keyPressBody: true` 。新增一种机制作为默认，快捷键只对当前 focus 的模态框生效。

2. 支持组合快捷键，如 Ctrl、Command、Alt、Shift 等。

3. 对图标型按钮添加了快捷键支持。

4. 给所有模态框预设添加 Escape 键关闭，给所有 confirm 模态框预设添加 Enter 键确认。

2023-01-26 14:29 UTC, dragon-fish approved these changes
```
机智的小鱼君@moegirl 22:25:47
Plugins#20怎么办，不想看了，直接合吧，有问题再revert

Bhsd@LLWiki 22:25:59
好。
```

2023-02-01 12:54 UTC, dragon-fish approved these changes

2023-02-01 13:25 UTC, merged