Update cm6.js
InPageEdit/Plugins pull request #50
Opened 2024-02-01 03:41 UTC by bhsd-harry

大更新，现在用户可自选开启的CodeMirror 6插件

2024-02-01 03:48 UTC, bhsd-harry commented
@dragon-fish 如果要转正的话，覆盖移动到`script.js`吗？

2024-02-21 02:40 UTC, dragon-fish requested changes

2024-02-21 02:40 UTC, dragon-fish commented on src/plugins/code-mirror/style.css
> -}
删除此段落是否会影响仍在使用 cm5 的用户？

2024-02-21 02:41 UTC, bhsd-harry commented on src/plugins/code-mirror/style.css
> -}
这个PR打算彻底将CM5升级为CM6。

2024-02-21 02:43 UTC, dragon-fish commented
https://github.com/inpageedit/Plugins/blob/3d46a1caf0a138b8e5e382c1f10db85646871541/src/index.json#L26-L30

怎么说

2024-02-21 02:46 UTC, bhsd-harry commented
稍等，那我还是先revert回去吧。

2024-02-21 02:47 UTC, dragon-fish commented
> https://github.com/inpageedit/Plugins/blob/3d46a1caf0a138b8e5e382c1f10db85646871541/src/index.json#L26-L30
> 
> 怎么说

目前 IPE 还没有自动移除失效插件的能力，这是设计上的缺陷，要么就保留 cm6.js 这个文件，内容换成加载 script.js

2024-02-21 02:50 UTC, bhsd-harry commented
我想了想CM6还是先保留BETA吧，再等一段时间的用户反馈。

2024-02-21 03:00 UTC, dragon-fish approved these changes
LGTM

2024-02-21 03:03 UTC, dragon-fish commented
要不同步更新一下文档，简单讲一下怎么配置 cm6？

https://github.com/inpageedit/Documentation/blob/b4f753f5a8d2dd4760dd2b7f0df5e25265c62056/src/guide/usage/preference.md?plain=1#L39

2024-02-21 03:04 UTC, merged

2024-02-21 03:05 UTC, dragon-fish commented
> 要不同步更新一下文档，简单讲一下怎么配置 cm6？
> 
> https://github.com/inpageedit/Documentation/blob/b4f753f5a8d2dd4760dd2b7f0df5e25265c62056/src/guide/usage/preference.md?plain=1#L39

也可以另开一个“插件”主题，把 CodeMirror 的文档移进去

2024-02-21 03:05 UTC, bhsd-harry commented
> 要不同步更新一下文档，简单讲一下怎么配置 cm6？

CM6有一个固有缺陷，无法从外部更换样式，这个我得先观望一下MW的人怎么解决。