feat: introduce monaco editor
InPageEdit/Plugins pull request #51
Opened 2024-03-02 16:28 UTC by dragon-fish

2024-03-03 01:54 UTC, bhsd-harry commented on src/plugins/monaco/README.md
> +Don't use this plugin with the `CodeEditor` extension, as it may cause conflicts.
`CodeMirror` or `CodeEditor`?

2024-03-03 01:54 UTC, bhsd-harry commented on src/plugins/monaco/env.d.ts
> +    monaco: typeof monaco
How about

```ts
declare global {
    const monaco: typeof monaco
}
```

2024-03-03 03:06 UTC, bhsd-harry commented
字体大小只有12px，要不要放大一点？另外Markdown格式的intelliSense我这儿都无法显示。

2024-03-04 07:17 UTC, AlPha5130 requested changes
等改完这些问题再说吧（

2024-03-07 07:04 UTC, bhsd-harry commented
我还发现关闭模态框时总是会提示有未保存的编辑，即使什么都没改。

2024-03-07 07:24 UTC, bhsd-harry requested changes

2024-03-07 07:24 UTC, bhsd-harry commented on src/plugins/monaco/script.js
> +          'https://cdn.jsdelivr.net/npm/@wikimedia/types-wikimedia@0.4.2/MediaWiki.d.ts',
为什么只有这个指定了版本号？

2024-03-07 07:24 UTC, bhsd-harry commented on src/plugins/monaco/script.js
> +          }, 50)
我猜想可能是由于这个延时，下一行的`onDidChangeContent`总是被触发，导致退出编辑时总是提示有未保存的编辑。

2024-03-09 09:54 UTC, bhsd-harry commented
> 另外Markdown格式的intelliSense我这儿都无法显示。

我知道了，`<code>`的字体颜色是黑色，结果黑色背景下文字看不见了。

2024-03-31 09:34 UTC, merged